version: "3.9"
services:
  api-gateway:
    build: .
    container_name: api_gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: 8080
      SECURITY_JWT_HMAC_SECRET: ${JWT_HMAC_SECRET}
      ROUTES_AUTH: ${AUTH_SERVICE_URL}
      ROUTES_USERS: ${USERS_BUDGETS_URL}
      ROUTES_TRANSACTIONS: ${TRANSACTIONS_URL}
      ROUTES_CATEGORIZATION: ${CATEGORIZATION_URL}
      ROUTES_FORECASTS: ${FORECASTS_URL}

    depends_on:
      - auth-service
