version: "3.9"
services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=api-gateway
    depends_on:
      - auth-service
